-- Migration: 20260522000000_create_projects_table.sql

-- First, ensure the profiles table exists (NextAuth users)
CREATE TABLE IF NOT EXISTS profiles (
  sub text primary key,
  email text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create the projects table
CREATE TABLE IF NOT EXISTS projects (
  id bigint generated by default as identity primary key,
  user_id_sub text references profiles(sub) not null,
  spreadsheet_id text not null,
  "name" text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- Note: Since we are using NextAuth, we might need to handle the RLS policies 
-- differently if not using Supabase Auth. For MVP, we'll allow service_role access.

-- Policy to allow users to see their own profile
CREATE POLICY "Users can see their own profile"
ON profiles
FOR SELECT
USING (true); -- Simplified for MVP, should be scoped if using Supabase Auth

-- Policy to allow users to see their own projects
CREATE POLICY "Users can see their own projects"
ON projects
FOR SELECT
USING (true); -- Simplified for MVP
