# Generated by scripts/generate_reclass_rules.mjs from contracts/reclass_rules.v1.yaml.
# Do not edit by hand.
from __future__ import annotations

from typing import Any, Dict

RULE_REGISTRY: Dict[str, Dict[str, Any]] = {
    "R000": {
        "category": "Excluded",
        "reason_zh": "Type 为 Sharing 的记录（仅限 Final Detail）排除在成本重分类之外",
        "reason_en": "Rows with Type='Sharing' (Final Detail only) are excluded from cost reclassification",
        "semantics": "sharing_exclusion",
        "sheet_scope": ("Final Detail",),
    },
    "R101": {
        "category": "GC",
        "reason_zh": "Unit Code 包含 General Condition 关键字",
        "reason_en": "Unit Code contains 'General Condition' keyword",
        "semantics": "gc_keyword",
        "sheet_scope": ("Payable", "Final Detail"),
    },
    "R102": {
        "category": "Consulting",
        "reason_zh": "结算前：WTC (4) + 供应商为 WB Texas Consulting LLC",
        "reason_en": "Before Settlement: WTC (4) + Vendor is WB Texas Consulting LLC",
        "semantics": "wtc_consulting_wbt",
        "sheet_scope": ("Payable", "Final Detail"),
    },
    "R103": {
        "category": "GC2",
        "reason_zh": "结算前：WTC (4) + 供应商非关联咨询商",
        "reason_en": "Before Settlement: WTC (4) + Non-associated consulting vendor",
        "semantics": "wtc_gc2",
        "sheet_scope": ("Payable", "Final Detail"),
    },
    "R104": {
        "category": "GC Income",
        "reason_zh": "结算前：Final GMP (1) + GC (5) + 供应商为 Wan Pacific",
        "reason_en": "Before Settlement: Final GMP (1) + GC (5) + Vendor is Wan Pacific",
        "semantics": "gmp_gc_income",
        "sheet_scope": ("Payable", "Final Detail"),
    },
    "R105": {
        "category": "GC",
        "reason_zh": "结算前：Final GMP (1) + GC (5) + 供应商非 Wan Pacific",
        "reason_en": "Before Settlement: Final GMP (1) + GC (5) + Vendor is not Wan Pacific",
        "semantics": "gmp_gc_standard",
        "sheet_scope": ("Payable", "Final Detail"),
    },
    "R106": {
        "category": "Income",
        "reason_zh": "结算前：Final GMP (1) + Fee (2) + 供应商为 Wan Pacific",
        "reason_en": "Before Settlement: Final GMP (1) + Fee (2) + Vendor is Wan Pacific",
        "semantics": "gmp_fee_income",
        "sheet_scope": ("Payable", "Final Detail"),
    },
    "R107": {
        "category": "ROE",
        "reason_zh": "结算前：标准 ROE 特征 (Final GMP/Fee)",
        "reason_en": "Before Settlement: Standard ROE features (Final GMP/Fee)",
        "semantics": "gmp_roe_standard",
        "sheet_scope": ("Payable", "Final Detail"),
    },
    "R108": {
        "category": "Direct",
        "reason_zh": "结算前：未命中任何 Scoping 标识（非 GMP 成本兜底）",
        "reason_en": "Before Settlement: No Scoping status matched (Direct fallback)",
        "semantics": "non_gmp_direct",
        "sheet_scope": ("Payable", "Final Detail"),
    },
    "R201": {
        "category": "ACC",
        "reason_zh": "结算后：仅有 Final Date 且无 Incurred Date",
        "reason_en": "After Settlement: Only Final Date present with no Incurred Date",
        "semantics": "post_settlement_acc",
        "sheet_scope": ("Final Detail",),
    },
    "R202": {
        "category": "RACC",
        "reason_zh": "结算后：命中跨表或成对的 RACC 配对键",
        "reason_en": "After Settlement: Matched cross-sheet or paired RACC key",
        "semantics": "post_settlement_racc",
        "sheet_scope": ("Payable", "Final Detail"),
    },
    "R203": {
        "category": "TBD",
        "reason_zh": "结算后：(有效日期 > TBD Acceptance Date) 且 (Scoping J列 = 6)",
        "reason_en": "After Settlement: (Date > TBD Acceptance Date) AND (Scoping Column J = 6)",
        "semantics": "post_settlement_tbd",
        "sheet_scope": ("Payable", "Final Detail"),
    },
    "R204": {
        "category": "RACC2",
        "reason_zh": "结算后：发生日 <= 保修到期日，且符合 Final GMP/Fee ROE 特征",
        "reason_en": "After Settlement: Date <= Warranty Expiry AND matches Final GMP/Fee ROE features",
        "semantics": "post_settlement_racc2",
        "sheet_scope": ("Payable", "Final Detail"),
    },
    "R205": {
        "category": "EXP",
        "reason_zh": "结算后支出兜底",
        "reason_en": "After Settlement: General expense fallback",
        "semantics": "post_settlement_exp",
        "sheet_scope": ("Payable", "Final Detail"),
    },
    "R301": {
        "category": "RACC",
        "reason_zh": "Restore: 结算前后窗口修正（Payable 端，独立判定）",
        "reason_en": "Restore: Settlement-window correction for Payable side (standalone)",
        "semantics": "restore_payable_racc",
        "sheet_scope": ("Payable",),
    },
    "R302": {
        "category": "ACC",
        "reason_zh": "Restore: 结算前后窗口修正（Final Detail 端，独立判定）",
        "reason_en": "Restore: Settlement-window correction for Final Detail side (standalone)",
        "semantics": "restore_final_detail_acc",
        "sheet_scope": ("Final Detail",),
    },
}
