#!/usr/bin/env node
import { readFileSync, writeFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const appRoot = path.resolve(scriptDir, "..");
const contractPath = path.join(appRoot, "contracts", "reclass_rules.v1.yaml");
const tsOutputPath = path.join(appRoot, "src", "lib", "generated-reclass-rules.ts");
const pyOutputPath = path.join(appRoot, "api", "logic", "aiwb_finance", "generated_reclass_rules.py");
const isCheck = process.argv.includes("--check");

function readContract() {
  const lines = readFileSync(contractPath, "utf8").split(/\r?\n/);
  const rules = [];
  let current = null;
  let listKey = null;

  for (const rawLine of lines) {
    if (!rawLine.trim() || rawLine.trim().startsWith("#")) {
      continue;
    }

    const itemMatch = rawLine.match(/^  - id: (.+)$/);
    if (itemMatch) {
      if (current) {
        rules.push(current);
      }
      current = { id: itemMatch[1].trim(), sheet_scope: [] };
      listKey = null;
      continue;
    }

    if (!current) {
      continue;
    }

    const scalarMatch = rawLine.match(/^    ([a-z_]+):(?: (.*))?$/);
    if (scalarMatch) {
      const [, key, value = ""] = scalarMatch;
      if (key === "sheet_scope") {
        listKey = key;
        current.sheet_scope = [];
      } else {
        listKey = null;
        current[key] = value.trim();
      }
      continue;
    }

    const listItemMatch = rawLine.match(/^      - (.+)$/);
    if (listItemMatch && listKey === "sheet_scope") {
      current.sheet_scope.push(listItemMatch[1].trim());
    }
  }

  if (current) {
    rules.push(current);
  }

  validateRules(rules);
  return rules;
}

function validateRules(rules) {
  const requiredFields = ["id", "category", "semantics", "reason_zh", "reason_en"];
  const seen = new Set();
  for (const rule of rules) {
    for (const field of requiredFields) {
      if (!rule[field]) {
        throw new Error(`Rule ${rule.id || "(unknown)"} is missing ${field}`);
      }
    }
    if (!Array.isArray(rule.sheet_scope) || rule.sheet_scope.length === 0) {
      throw new Error(`Rule ${rule.id} is missing sheet_scope`);
    }
    if (seen.has(rule.id)) {
      throw new Error(`Duplicate rule id ${rule.id}`);
    }
    seen.add(rule.id);
  }
}

function generatedHeader(commentPrefix) {
  return [
    `${commentPrefix} Generated by scripts/generate_reclass_rules.mjs from contracts/reclass_rules.v1.yaml.`,
    `${commentPrefix} Do not edit by hand.`,
    "",
  ].join("\n");
}

function renderTs(rules) {
  return `${generatedHeader("//")}export interface GeneratedReclassRule {
  rule_id: string;
  category: string;
  semantics: string;
  sheet_scope: string[];
  reason_zh: string;
  reason_en: string;
}

export const GENERATED_RECLASS_RULES: GeneratedReclassRule[] = ${JSON.stringify(
    rules.map((rule) => ({
      rule_id: rule.id,
      category: rule.category,
      semantics: rule.semantics,
      sheet_scope: rule.sheet_scope,
      reason_zh: rule.reason_zh,
      reason_en: rule.reason_en,
    })),
    null,
    2,
  )};
`;
}

function pyString(value) {
  return JSON.stringify(value).replace(/false/g, "False").replace(/true/g, "True").replace(/null/g, "None");
}

function renderPy(rules) {
  const body = rules
    .map((rule) => {
      return `    ${pyString(rule.id)}: {
        "category": ${pyString(rule.category)},
        "reason_zh": ${pyString(rule.reason_zh)},
        "reason_en": ${pyString(rule.reason_en)},
        "semantics": ${pyString(rule.semantics)},
        "sheet_scope": (${rule.sheet_scope.map(pyString).join(", ")}${rule.sheet_scope.length === 1 ? "," : ""}),
    },`;
    })
    .join("\n");

  return `${generatedHeader("#")}from __future__ import annotations

from typing import Any, Dict

RULE_REGISTRY: Dict[str, Dict[str, Any]] = {
${body}
}
`;
}

function assertCurrent(filePath, expected) {
  let actual = "";
  try {
    actual = readFileSync(filePath, "utf8");
  } catch {
    throw new Error(`${path.relative(appRoot, filePath)} is missing; run scripts/generate_reclass_rules.mjs`);
  }
  if (actual !== expected) {
    throw new Error(`${path.relative(appRoot, filePath)} is stale; run scripts/generate_reclass_rules.mjs`);
  }
}

const rules = readContract();
const tsOutput = renderTs(rules);
const pyOutput = renderPy(rules);

if (isCheck) {
  assertCurrent(tsOutputPath, tsOutput);
  assertCurrent(pyOutputPath, pyOutput);
  process.stdout.write("generated reclassification rules are current\n");
} else {
  writeFileSync(tsOutputPath, tsOutput);
  writeFileSync(pyOutputPath, pyOutput);
  process.stdout.write("generated reclassification rules updated\n");
}
