import { build109CompareSnapshot, buildAuditSnapshot } from "@/lib/audit-dashboard";

describe("audit dashboard phase 1 contract", () => {
  it("builds phase1 workbench snapshot with external recon, reclass audit, and 109 compare", () => {
    const snapshot = buildAuditSnapshot({
      projectName: "Sandy Cove",
      kpiRows: [],
      payableRows: [],
      finalDetailRows: [],
      drawRequestRows: [],
      unitMasterRows: [],
      scopingRows: [],
      rows109: [],
    });

    expect(snapshot.audit_tabs.external_recon).toBeDefined();
    expect(snapshot.audit_tabs.reclass_audit).toBeDefined();
    expect(snapshot.audit_tabs.compare_109).toBeDefined();
  });

  it("aggregates payable/final/draw discrepancies and unit budget variance summaries", () => {
    const snapshot = buildAuditSnapshot({
      projectName: "Sandy Cove",
      kpiRows: [],
      payableRows: [
        [
          "Category",
          "Rule_ID",
          "",
          "",
          "GMP",
          "Fee",
          "WTC",
          "",
          "",
          "Year",
          "",
          "GuId",
          "Seq No.",
          "Pay Status",
          "Vendor",
          "Type",
          "Account Code",
          "Invoice No",
          "Invoice Description",
          "Invoice Date",
          "Amount",
          "Incurred Date",
          "Pay Due Date",
          "Pay Type",
          "Check System",
          "Check No",
          "Check Date",
          "Check Amount",
          "Clear Date",
          "Status",
          "Company Code",
          "Company",
          "Division",
          "Project",
          "Activity No",
          "Description",
          "Fast Code",
          "Unit Code",
          "Cost Code",
          "Cost Name",
          "Journal Code",
          "Cost Account Name",
          "Cost State",
        ],
        [
          "Direct",
          "R108",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "2025",
          "",
          "guid-1",
          "1",
          "Clear",
          "Vendor A",
          "Type 1",
          "",
          "INV-1",
          "",
          "2025-01-01",
          "100",
          "2025-01-01",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "ACT-1",
          "",
          "",
          "U1",
          "1SF300",
          "",
          "",
          "",
          "Direct",
        ],
        [
          "Consulting",
          "R102",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "2025",
          "",
          "guid-2",
          "2",
          "Clear",
          "Vendor B",
          "Type 2",
          "",
          "INV-2",
          "",
          "2025-01-03",
          "50",
          "2025-01-03",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "ACT-2",
          "",
          "",
          "U2",
          "2HD500",
          "",
          "",
          "",
          "Consulting",
        ],
      ],
      finalDetailRows: [
        [
          "Category",
          "Rule_ID",
          "",
          "",
          "",
          "结算年份",
          "结算金额",
          "预提金额",
          "预提后发生年份",
          "年度合计金额",
          "Incurred Y",
          "",
          "RowId",
          "#",
          "Final Date",
          "Final Amount",
          "Posting Date 1",
          "Posting Date 2",
          "Release Date",
          "Incurred Date",
          "Unit Code",
          "Type",
          "Activity No.",
          "Activity",
          "Cost State",
          "Cost Code",
          "Journal Code",
          "Amount",
        ],
        [
          "Direct",
          "R108",
          "",
          "",
          "",
          "2025",
          "",
          "",
          "",
          "",
          "",
          "",
          "row-1",
          "1",
          "2025-02-01",
          "",
          "",
          "",
          "",
          "2025-01-01",
          "U1",
          "Type 1",
          "ACT-1",
          "",
          "Direct",
          "1SF300",
          "",
          "100",
        ],
      ],
      drawRequestRows: [
        ["", "", "", "", "Project Name："],
        [
          "",
          "",
          "",
          "",
          "Sql",
          "Draw Date",
          "Draw Invoice",
          "Unit Code",
          "Complete Stage",
          "Complete Date",
          "Previous Stages",
          "Days",
          "Estimated Date",
          "Report Date",
          "Incurred Date",
          "Invoiced Date",
          "Invoiced No",
          "Activity No",
          "Activity",
          "Cost Code",
          "Well Code",
          "Type",
          "Released Date",
          "Vendor No.",
          "Vendor",
          "Amount",
        ],
        [
          "",
          "",
          "",
          "",
          "1",
          "2025-01-31",
          "DRAW-1",
          "U1",
          "",
          "",
          "",
          "",
          "",
          "2025-01-05",
          "2025-01-01",
          "2025-01-10",
          "INV-1",
          "ACT-1",
          "",
          "1SF300",
          "",
          "Type 1",
          "",
          "",
          "Vendor A",
          "100",
        ],
      ],
      unitMasterRows: [
        ["Total", "1000", "200", "800"],
        ["Unit Code", "Total Budget", "GC Budget", "WIP Budget"],
        ["U1", "1000", "200", "800"],
      ],
      scopingRows: [
        [
          "",
          "",
          "Group Number",
          "Group Name",
          "GMP",
          "Fee",
          "WIP",
          "WTC",
          "GC",
          "TBD",
          "",
          "",
          "Budget",
          "Incurred amount",
        ],
        ["", "", "300", "Test Group", "1", "", "", "", "", "", "", "", "1000", "100"],
      ],
      rows109: [],
    });

    expect(snapshot.audit_tabs.external_recon.recon_by_cost_state.length).toBeGreaterThan(0);
    expect(snapshot.audit_tabs.external_recon.unit_budget_variances.length).toBeGreaterThan(0);
    expect(snapshot.audit_tabs.external_recon.invoice_match_overview).toEqual(
      expect.objectContaining({
        payable_total_invoices: 2,
        final_total_invoices: 1,
        draw_total_invoices: 1,
        matched_to_final: 1,
        matched_to_draw: 1,
        matched_to_both: 1,
        payable_unmatched: 1,
        final_only: 0,
        draw_only: 0,
      }),
    );
    expect(snapshot.audit_tabs.scoping_logic.length).toBeGreaterThan(0);
  });

  it("builds reclassification totals from payable AQ, excludes R000, and sorts rules by id", () => {
    const snapshot = buildAuditSnapshot({
      projectName: "Sandy Cove",
      kpiRows: [],
      payableRows: [
        [
          "ROE",
          "R107",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "Vendor A",
          "",
          "",
          "",
          "",
          "",
          "100",
          "2025-01-01",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "U1",
          "1SF300",
          "",
          "",
          "",
          "",
          "",
          "Direct",
        ],
        [
          "GC",
          "R105",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "Vendor B",
          "",
          "",
          "",
          "",
          "",
          "200",
          "2025-01-02",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "U2",
          "1SF500",
          "",
          "",
          "",
          "",
          "",
          "ROE",
        ],
        [
          "Direct",
          "R000",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "Vendor C",
          "",
          "",
          "",
          "",
          "",
          "300",
          "2025-01-03",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "U3",
          "1SF700",
          "",
          "",
          "",
          "Direct",
        ],
      ],
      finalDetailRows: [],
      drawRequestRows: [],
      unitMasterRows: [],
      scopingRows: [],
      rows109: [],
    });

    expect(snapshot.workflow_stage).toBe("Reclass Audit");
    expect(snapshot.audit_tabs.reclass_audit.overview.diff_amount).toBe(300);
    expect(snapshot.audit_tabs.reclass_audit.overview.old_total).toBe(300);
    expect(snapshot.audit_tabs.reclass_audit.overview.new_total).toBe(300);
    expect(snapshot.audit_tabs.reclass_audit.overview.diff_invoice_count).toBe(2);
    expect(snapshot.audit_tabs.reclass_audit.category_rows).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ category: "Direct", old_total: 100, new_total: 0, diff_amount: -100 }),
        expect.objectContaining({ category: "ROE", old_total: 200, new_total: 100, diff_amount: -100 }),
        expect.objectContaining({ category: "GC", old_total: 0, new_total: 200, diff_amount: 200 }),
      ]),
    );
    expect(snapshot.audit_tabs.reclass_audit.rule_rows[0].rule_id).toBe("R105");
    expect(snapshot.audit_tabs.reclass_audit.rule_rows[1].rule_id).toBe("R107");
    expect(snapshot.audit_tabs.reclass_audit.rule_rows).toHaveLength(2);
    expect(snapshot.audit_tabs.reclass_audit.invoice_rows).toHaveLength(2);
    expect(snapshot.audit_tabs.reclass_audit.sankey.nodes).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ name: "Old Direct" }),
        expect.objectContaining({ name: "Old ROE" }),
        expect.objectContaining({ name: "New ROE" }),
        expect.objectContaining({ name: "New GC" }),
      ]),
    );
    expect(snapshot.audit_tabs.reclass_audit.sankey.links).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ value: 100 }),
        expect.objectContaining({ value: 200 }),
      ]),
    );
  });

  it("builds 109 compare rows for revenue, cost, and gross profit across years", () => {
    const rows109 = [
      ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
      ...Array.from({ length: 60 }, () => Array.from({ length: 18 }, () => "")),
    ];
    rows109[9][5] = "2024";
    rows109[9][6] = "2025";
    rows109[9][7] = "2026";
    rows109[9][8] = "2027";
    rows109[9][9] = "2028";
    rows109[9][10] = "2029";
    rows109[18][5] = 100;
    rows109[18][12] = 90;
    rows109[29][5] = 60;
    rows109[29][12] = 70;
    rows109[51][5] = 40;
    rows109[51][12] = 20;

    const compare109 = build109CompareSnapshot(rows109);
    expect(compare109.metric_rows).toHaveLength(3);
    expect(compare109.metric_rows[0].year_rows[0].diff).toBe(10);
    expect(compare109.metric_rows[0].year_rows[0]).toEqual(
      expect.objectContaining({
        year_offset: 0,
        year_label: "2024",
        company: 100,
        audit: 90,
        diff: 10,
      }),
    );
  });
});
